"""initial migration including employee id

Revision ID: 7f673f8d6c58
Revises: 
Create Date: 2024-04-17 20:06:21.735614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f673f8d6c58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_info',
    sa.Column('sn', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=100), nullable=False),
    sa.Column('dimension', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('sn', name=op.f('pk_column_info'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_user_employee_id'))
    )
    op.create_table('usage_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('technique', sa.String(length=100), nullable=False),
    sa.Column('mobile_phase_a', sa.String(length=100), nullable=True),
    sa.Column('mobile_phase_b', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['column_info.sn'], name=op.f('fk_usage_entry_column_id_column_info')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_usage_entry_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_entry'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_entry')
    op.drop_table('user')
    op.drop_table('column_info')
    # ### end Alembic commands ###
