"""model modified for date and reference

Revision ID: b61487027753
Revises: fee50f7575cc
Create Date: 2024-04-22 17:49:27.647301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61487027753'
down_revision = 'fee50f7575cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('column_info', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('usage_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_entry', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('column_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
