"""fixed Column sn datatype

Revision ID: c74b814f5b49
Revises: 7f673f8d6c58
Create Date: 2024-04-18 13:23:15.846383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74b814f5b49'
down_revision = '7f673f8d6c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('column_info', schema=None) as batch_op:
        batch_op.alter_column('sn',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('column_info', schema=None) as batch_op:
        batch_op.alter_column('sn',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
